repos:
  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.1.4
    hooks:
      - id: isort
